apiVersion: v1
kind: Pod
metadata:
  name: nodeapp
  labels:
    app: nodeapp
spec:
  replicas: 4  # Total number of pods (2 pods per node)
  containers:
    - name: nodeapp
      image: cfusionjo/nodeapp:tagVersion
      ports:
        - containerPort: 8080
